FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /api
COPY backend/requirements.txt /api/
# COPY backend/manage.py /api/
RUN pip install -r requirements.txt
EXPOSE 8000
COPY . /api/
