FROM node:alpine
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/ManiTiendita/package*.json /app/
COPY frontend/ManiTiendita/vite.config.js /app/
# RUN npm ci --only=productions

RUN npm install
COPY . /app/
#RUN npm run build
EXPOSE 3001
CMD [ "npm","run","dev" ]