# Generated by Django 3.2.20 on 2023-07-14 03:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('fecha_reg', models.DateTimeField(default=datetime.datetime(2023, 7, 14, 3, 41, 44, 992869))),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_reg', models.DateTimeField(default=datetime.datetime(2023, 7, 14, 3, 41, 44, 993235))),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_largo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(max_length=10, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'UnidadMedida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción de Producto')),
                ('precio_compra', models.FloatField(verbose_name='Precio de Compra')),
                ('precio_venta', models.FloatField(verbose_name='Precio de Venta')),
                ('existencias', models.FloatField(default=0, verbose_name='Nombre')),
                ('fecha_reg', models.DateTimeField(default=datetime.datetime(2023, 7, 14, 3, 41, 44, 993807))),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.marca')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
